### ISSUE TITLE
Project plan to-do list

### ISSUE THREAD

**Issue by kaob1991** [kaob1991/pands-project2021#1]
- [x]  figured out how to add image to summary

- [x] listed all current references

- [x] consider headings for readme. 

- [x] do i have enough on the "history" of the dataset? 

- [x] ensure I describe each part of the program and a summary of what it does

- [x] ensure I explain why python is used- how good it is at analysing data

- [x] modify code on readme to account for changes

- [x] comment on everything in code and match that to readme 

- [x]  Histograms of each variable to png files- try and find out why histos are not working correctly- all amalgamating when code is running

- [x] write up on l-plot, facetgrid, etc 

- [x] need to look at why the histograms are taking in data from the previous example.

- [x] Need to change y axis to frequency. 

- [x] scatterplot within analysis.py

- [x] Research into data analysis done on data set 

- [x] prep analysis.py with modules. (pandas, matplotlib, seaborn, numpy)

- [x] import dataset into analysis.py

- [x] double check that I can output to a textfile

**Comment by kaob1991** [comment]
- [ ]  Histograms of each variable to png files
- [ ] scatterplot within analysis.py

**Comment by kaob1991** [comment]
Mode and media of each species and overall database

**Comment by kaob1991** [comment]
need to look at why the histograms are taking in data from the previous example.

**Comment by kaob1991** [comment]
write up on l-plot, facetgrid, etc
